[tool.ruff]
extend = "../pyproject.toml"


[tool.ruff.lint]
extend-ignore = [
    "ARG002", # maybe cleanup later - unused method argument
    "COM812", # cleanup later
    "FBT002", # cleanup soon - boolean positional argument
    "FLY002", # maybe cleanup later - f-string instead of join
    "G002", # cleanup soon - logging statement uses %
    "I001", # maybe cleanup later - import block unsorted
    "PLR0912", # maybe cleanup later
    "PLW2901", # maybe cleanup later
    "RET504", # maybe cleanup later - unnecessary assignment before return
    "RET506", # maybe cleanup later - unnecessary elif after raise
    "RUF012", # cleanup later
    "RSE102", # maybe cleanup later
    "S608", # cleanup soon - possible sql injection
    "UP020", # cleanup soon - use builtin 'open'
    "UP024", # maybe cleanup later - aliased errors
    "UP032", # cleanup later - f-string instead of format
]


[tool.towncrier]
package = "devpi_postgresql"
filename = "CHANGELOG"
directory = "news/"
title_format = "{version} ({project_date})"
template = "news/_template.rst"

  [[tool.towncrier.type]]
  directory = "removal"
  name = "Deprecations and Removals"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "feature"
  name = "Features"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "bugfix"
  name = "Bug Fixes"
  showcontent = true

  [[tool.towncrier.type]]
  directory = "other"
  name = "Other Changes"
  showcontent = true
