[tool.ruff]
extend = "../pyproject.toml"


[tool.ruff.format]
exclude = [
    "devpi_debugging/main.py",
    "devpi_debugging/views.py",
    "setup.py",
]


[tool.ruff.lint]
extend-ignore = [
    "ARG001", # maybe cleanup later - unused function argument
    "B007", # maybe cleanup later
    "BLE001", # cleanup soon - blind exception
    "I001", # maybe cleanup later - import block unsorted
    "PERF401", # maybe cleanup later - list comprehension
    "PIE808", # maybe cleanup later
    "PLR0912", # maybe cleanup later
    "SIM102", # maybe cleanup later
    "SIM114", # maybe cleanup later
]
